micronaut:
  application:
    name: footballmanager
datasources:
  default:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/footballerdb
    username: postgres
    password: mysecretpassword
    # schema-generate: CREATE_DROP
    # dialect: postgres
