micronaut:
  application:
    name: footballermanager
datasources:
  default:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/footballerdb
    username: postgres
    password: mysecretpassword
    schema-generate: CREATE  # or CREATE_DROP if you want the table to be re-created with each app start
    dialect: postgres
