micronaut:
  application:
    name: footballmanager
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/footballerdb
    driverClassName: org.postgresql.Driver
    username: postgres
    password: mysecretpassword
    schema-generate: CREATE_DROP
    dialect: POSTGRES

#datasources:
#  default:
#    url: jdbc:h2:mem:devDb
#    driverClassName: org.h2.Driver
#    username: sa
#    password: ''
#    schema-generate: CREATE_DROP
#    dialect: H2
