datasources:
  default:
    # Use in-memory H2 in PostgreSQL mode
    url: jdbc:h2:mem:devDb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2
